// Common tourist destinations
export const LOCATIONS = [
  // Popular Cities
  "Paris, France",
  "Tokyo, Japan",
  "New York City, USA",
  "London, UK",
  "Rome, Italy",
  "Barcelona, Spain",
  "Dubai, UAE",
  "Singapore",
  "Bangkok, Thailand",
  "Sydney, Australia",
  "Amsterdam, Netherlands",
  "Berlin, Germany",
  "Venice, Italy",
  "Prague, Czech Republic",
  "Istanbul, Turkey",
  "Hong Kong",
  "Seoul, South Korea",
  "Rio de Janeiro, Brazil",
  "Cape Town, South Africa",
  "Mumbai, India",
  
  // Countries
  "France",
  "Japan",
  "Italy",
  "Spain",
  "United States",
  "United Kingdom",
  "Australia",
  "Germany",
  "Canada",
  "Thailand",
  "Greece",
  "Portugal",
  "Switzerland",
  "New Zealand",
  "Norway",
  "Sweden",
  "Brazil",
  "Mexico",
  "Egypt",
  "Morocco"
].sort();
